# Generated by Django 3.2.15 on 2023-01-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('cuisine', models.CharField(max_length=50)),
                ('num_of_chefs', models.IntegerField(default=1)),
            ],
        ),
    ]
